<h1><?= $title ?></h1>
<form method="POST">
    <label for="name">Nom du laboratoire</label>
    <input type="text" name="name" id="name">
    <label for="logo">logo</label>
    <input type="text" name="logo" id="logo">
    <label for="description">Description</label>
    <textarea id="description" name="description">Description</textarea>
    <label for="contact">Contact</label>
    <input id="contact" name="contact">
    <input type="submit" value="Valider">

</form>