<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= $router->getWwwPath() ?>/css/style.css" >
    <link rel="stylesheet" href="<?= $router->getWwwPath() ?>/css/normalize.css" >

    <title>pharmacie<?php if(isset($title)) { echo " - ".$title; } ?></title>
</head>
<body>
<?php foreach ($flashBag->getAllMessages() as $message): ?>
<p class="flashbag" ><?= $message; ?></p>
<?php endforeach ?>
<main>

<h1>pharmacie</h1>
    <?php include $templatePath ?>


</main>
</body>
</html>